import { PDFDocument, rgb, StandardFonts } from "pdf-lib"
import { format } from "date-fns"
import type { Id } from "@/convex/_generated/dataModel"

// Define the report data structure
export interface DamageReportData {
  // Vehicle information
  vehicle: {
    id: Id<"vehicles">
    make: string
    model: string
    year: number
    vin: string
    licensePlate?: string
    color?: string
    mileage?: number
  }
  // Client information
  client: {
    id: Id<"clients">
    name: string
    email?: string
    phone?: string
  }
  // Assessment information
  assessment: {
    id: Id<"assessments">
    assessmentNumber: string
    assessmentDate: number
    status: string
    completedAt?: number
    notes?: string
    overallCondition?: string
    aiSummary?: string
  }
  // Damage information
  damages: Array<{
    id: string
    type: string
    severity: string
    location: string
    description?: string
    confidence?: number
    imageUrl?: string
  }>
  // Repair recommendations
  recommendations: Array<{
    id: string
    service: string
    description: string
    priority: string
    estimatedCost?: number
  }>
  // Report metadata
  metadata: {
    generatedBy: string
    generatedAt: number
    organizationName: string
    organizationLogo?: string
  }
}

/**
 * Generates a PDF damage report based on the provided data
 */
export async function generateDamageReport(data: DamageReportData): Promise<Uint8Array> {
  // Create a new PDF document
  const pdfDoc = await PDFDocument.create()

  // Add a blank page
  const page = pdfDoc.addPage([850, 1100])

  // Get the standard font
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  // Set some basic properties
  const { width, height } = page.getSize()
  const margin = 50
  let y = height - margin
  const lineHeight = 20

  // Add the report title
  page.drawText("VEHICLE DAMAGE ASSESSMENT REPORT", {
    x: margin,
    y,
    size: 24,
    font: boldFont,
    color: rgb(0, 0.68, 0.6), // #00ae98 in RGB
  })
  y -= lineHeight * 2

  // Add the report metadata
  page.drawText(`Report #: ${data.assessment.assessmentNumber}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Generated: ${format(data.metadata.generatedAt, "PPpp")}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Generated By: ${data.metadata.generatedBy}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Organization: ${data.metadata.organizationName}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight * 2

  // Add a separator line
  page.drawLine({
    start: { x: margin, y },
    end: { x: width - margin, y },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  })
  y -= lineHeight

  // Add the vehicle information section
  page.drawText("VEHICLE INFORMATION", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0.68, 0.6),
  })
  y -= lineHeight * 1.5

  page.drawText(`Make: ${data.vehicle.make}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Model: ${data.vehicle.model}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Year: ${data.vehicle.year}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`VIN: ${data.vehicle.vin}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  if (data.vehicle.licensePlate) {
    page.drawText(`License Plate: ${data.vehicle.licensePlate}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }

  if (data.vehicle.color) {
    page.drawText(`Color: ${data.vehicle.color}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }

  if (data.vehicle.mileage) {
    page.drawText(`Mileage: ${data.vehicle.mileage.toLocaleString()} miles`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }
  y -= lineHeight

  // Add the client information section
  page.drawText("CLIENT INFORMATION", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0.68, 0.6),
  })
  y -= lineHeight * 1.5

  page.drawText(`Name: ${data.client.name}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  if (data.client.email) {
    page.drawText(`Email: ${data.client.email}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }

  if (data.client.phone) {
    page.drawText(`Phone: ${data.client.phone}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }
  y -= lineHeight

  // Add the assessment information section
  page.drawText("ASSESSMENT INFORMATION", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0.68, 0.6),
  })
  y -= lineHeight * 1.5

  page.drawText(`Assessment Date: ${format(data.assessment.assessmentDate, "PPP")}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  page.drawText(`Status: ${data.assessment.status.toUpperCase()}`, {
    x: margin,
    y,
    size: 12,
    font,
  })
  y -= lineHeight

  if (data.assessment.completedAt) {
    page.drawText(`Completed: ${format(data.assessment.completedAt, "PPP")}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }

  if (data.assessment.overallCondition) {
    page.drawText(`Overall Condition: ${data.assessment.overallCondition}`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight
  }

  if (data.assessment.notes) {
    page.drawText(`Notes:`, {
      x: margin,
      y,
      size: 12,
      font,
    })
    y -= lineHeight

    // Split notes into multiple lines if needed
    const notesLines = splitTextIntoLines(data.assessment.notes, 80)
    for (const line of notesLines) {
      page.drawText(line, {
        x: margin + 20,
        y,
        size: 12,
        font,
      })
      y -= lineHeight
    }
  }
  y -= lineHeight

  // Add the damage information section
  page.drawText("IDENTIFIED DAMAGES", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0.68, 0.6),
  })
  y -= lineHeight * 1.5

  if (data.damages.length === 0) {
    page.drawText("No damages identified.", {
      x: margin,
      y,
      size: 12,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    })
    y -= lineHeight
  } else {
    // Create a table-like structure for damages
    const damageTableX = [margin, margin + 100, margin + 200, margin + 300, margin + 500]

    // Table header
    page.drawText("Type", {
      x: damageTableX[0],
      y,
      size: 12,
      font: boldFont,
    })

    page.drawText("Severity", {
      x: damageTableX[1],
      y,
      size: 12,
      font: boldFont,
    })

    page.drawText("Location", {
      x: damageTableX[2],
      y,
      size: 12,
      font: boldFont,
    })

    page.drawText("Description", {
      x: damageTableX[3],
      y,
      size: 12,
      font: boldFont,
    })

    y -= lineHeight

    // Table separator
    page.drawLine({
      start: { x: margin, y: y + 5 },
      end: { x: width - margin, y: y + 5 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    })
    y -= lineHeight

    // Table rows
    for (const damage of data.damages) {
      const descriptionLines = damage.description ? splitTextIntoLines(damage.description, 40) : [""]

      page.drawText(damage.type, {
        x: damageTableX[0],
        y,
        size: 12,
        font,
      })

      page.drawText(damage.severity, {
        x: damageTableX[1],
        y,
        size: 12,
        font,
      })

      page.drawText(damage.location, {
        x: damageTableX[2],
        y,
        size: 12,
        font,
      })

      if (descriptionLines[0]) {
        page.drawText(descriptionLines[0], {
          x: damageTableX[3],
          y,
          size: 12,
          font,
        })
      }

      y -= lineHeight

      // Draw additional description lines if any
      for (let i = 1; i < descriptionLines.length; i++) {
        page.drawText(descriptionLines[i], {
          x: damageTableX[3],
          y,
          size: 12,
          font,
        })
        y -= lineHeight
      }

      // Add a small gap between damage entries
      y -= 5
    }
  }
  y -= lineHeight

  // Add the recommendations section
  page.drawText("REPAIR RECOMMENDATIONS", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0.68, 0.6),
  })
  y -= lineHeight * 1.5

  if (data.recommendations.length === 0) {
    page.drawText("No repair recommendations.", {
      x: margin,
      y,
      size: 12,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    })
    y -= lineHeight
  } else {
    // Create a table-like structure for recommendations
    const recTableX = [margin, margin + 150, margin + 250, margin + 450]

    // Table header
    page.drawText("Service", {
      x: recTableX[0],
      y,
      size: 12,
      font: boldFont,
    })

    page.drawText("Priority", {
      x: recTableX[1],
      y,
      size: 12,
      font: boldFont,
    })

    page.drawText("Description", {
      x: recTableX[2],
      y,
      size: 12,
      font: boldFont,
    })

    if (data.recommendations.some((r) => r.estimatedCost !== undefined)) {
      page.drawText("Est. Cost", {
        x: recTableX[3],
        y,
        size: 12,
        font: boldFont,
      })
    }

    y -= lineHeight

    // Table separator
    page.drawLine({
      start: { x: margin, y: y + 5 },
      end: { x: width - margin, y: y + 5 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    })
    y -= lineHeight

    // Table rows
    for (const rec of data.recommendations) {
      const descriptionLines = splitTextIntoLines(rec.description, 40)

      page.drawText(rec.service, {
        x: recTableX[0],
        y,
        size: 12,
        font,
      })

      page.drawText(rec.priority, {
        x: recTableX[1],
        y,
        size: 12,
        font,
      })

      if (descriptionLines[0]) {
        page.drawText(descriptionLines[0], {
          x: recTableX[2],
          y,
          size: 12,
          font,
        })
      }

      if (rec.estimatedCost !== undefined) {
        page.drawText(`$${rec.estimatedCost.toLocaleString()}`, {
          x: recTableX[3],
          y,
          size: 12,
          font,
        })
      }

      y -= lineHeight

      // Draw additional description lines if any
      for (let i = 1; i < descriptionLines.length; i++) {
        page.drawText(descriptionLines[i], {
          x: recTableX[2],
          y,
          size: 12,
          font,
        })
        y -= lineHeight
      }

      // Add a small gap between recommendation entries
      y -= 5
    }
  }
  y -= lineHeight * 2

  // Add AI summary if available
  if (data.assessment.aiSummary) {
    page.drawText("AI ASSESSMENT SUMMARY", {
      x: margin,
      y,
      size: 16,
      font: boldFont,
      color: rgb(0, 0.68, 0.6),
    })
    y -= lineHeight * 1.5

    const summaryLines = splitTextIntoLines(data.assessment.aiSummary, 90)
    for (const line of summaryLines) {
      page.drawText(line, {
        x: margin,
        y,
        size: 12,
        font,
      })
      y -= lineHeight
    }
  }

  // Add footer
  const footerY = margin
  page.drawLine({
    start: { x: margin, y: footerY + 15 },
    end: { x: width - margin, y: footerY + 15 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  })

  page.drawText(`Generated by SlickAssess - ${format(data.metadata.generatedAt, "PPpp")}`, {
    x: margin,
    y: footerY,
    size: 10,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })

  page.drawText("Page 1 of 1", {
    x: width - margin - 50,
    y: footerY,
    size: 10,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })

  // Serialize the PDFDocument to bytes
  return await pdfDoc.save()
}

/**
 * Helper function to split text into lines based on max width
 */
function splitTextIntoLines(text: string, maxCharsPerLine: number): string[] {
  const words = text.split(" ")
  const lines: string[] = []
  let currentLine = ""

  for (const word of words) {
    if (currentLine.length + word.length + 1 <= maxCharsPerLine) {
      currentLine += (currentLine ? " " : "") + word
    } else {
      lines.push(currentLine)
      currentLine = word
    }
  }

  if (currentLine) {
    lines.push(currentLine)
  }

  return lines
}
